apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adpulse.ad_manager_frontend.name }}
  namespace: {{ .Values.adpulse.namespace.name }}
  labels:
    {{ .Values.adpulse.ad_manager_frontend.labels | toYaml | nindent 4}}
spec:
  replicas: {{ .Values.adpulse.ad_manager_frontend.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.adpulse.ad_manager_frontend.selectorLabels | toYaml | nindent 6}}
  template:
    metadata:
      labels:
        {{ .Values.adpulse.ad_manager_frontend.selectorLabels | toYaml | nindent 8}}
    spec:
      serviceAccountName: {{ .Values.adpulse.ad_manager_frontend.serviceAccountName }}
      containers:
        - name: {{ .Values.adpulse.ad_manager_frontend.name }}
          image: "{{ .Values.adpulse.ad_manager_frontend.image.repository }}:{{ .Values.adpulse.ad_manager_frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://{{ .Values.adpulse.ad_manager_svc.name }}:{{ .Values.adpulse.ad_manager_svc.service.port }}"
            - name: REACT_APP_API_AD_SERVER_URL
              value: "http://{{ .Values.adpulse.ad_server_svc.name }}:{{ .Values.adpulse.ad_server_svc.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.adpulse.ad_manager_frontend.service.targetPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http