name: Build and Push to Docker Hub

on:
    push:
        branches:
            - main

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
    bump-version:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Bump version
          run: |
                old_version=$(cat version.txt)
                regex="([0-9]+)\.([0-9]+)\.([0-9]+)"
                if [[ $old_version =~ $regex ]]; then
                    major="${BASH_REMATCH[1]}"
                    minor="${BASH_REMATCH[2]}"
                    patch="${BASH_REMATCH[3]}"
                    new_patch=$((patch + 1))
                    new_version="${major}.${minor}.${new_patch}"
                    echo "Old version: $old_version"
                    echo "New version: $new_version"
                    echo $new_version > version.txt
                else
                    echo "Invalid version format: $old_version"
                fi

        - name: Commit changes
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add version.txt
            git commit -m "Bump version to $new_version"
            git push https://${{ secrets.PAT }}@github.com/${{ github.repository }} HEAD:main
    build:
        needs: bump-version
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build and push Docker image
              run: |
                    docker buildx create --use
                    docker buildx build --platform linux/amd64,linux/arm64 --push -t adpulse18/$(basename ${{ github.repository }}):$(cat version.txt) .